# Generated by Django 3.1.4 on 2020-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0002_auto_20201228_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtable',
            old_name='add_pri',
            new_name='cnt_amt',
        ),
        migrations.RenameField(
            model_name='testtable',
            old_name='add_sec',
            new_name='cnt_day',
        ),
        migrations.RenameField(
            model_name='testtable',
            old_name='address',
            new_name='cnt_year_month',
        ),
        migrations.RenameField(
            model_name='testtable',
            old_name='city',
            new_name='level',
        ),
        migrations.AddField(
            model_name='testtable',
            name='sgmt',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
