# Generated by Django 3.1.4 on 2021-01-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0003_auto_20201228_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_code', models.CharField(max_length=10)),
                ('apt_name', models.CharField(max_length=30)),
                ('apt_addr', models.CharField(max_length=100)),
                ('apt_born', models.CharField(max_length=8)),
                ('apt_indv', models.CharField(max_length=5)),
            ],
        ),
    ]
