# Generated by Django 3.1.4 on 2021-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0004_table2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table2',
            old_name='apt_indv',
            new_name='apt_indvs',
        ),
        migrations.AlterField(
            model_name='table2',
            name='apt_born',
            field=models.CharField(max_length=30),
        ),
    ]
